version: "3.7"

services:
  water_rights_visualizer:
    build: water_rights_visualizer
    container_name: water-rights-visualizer
    restart: always
    ports:
      - "80:8000"
    command: "npm run S3"

  drought:
    build:
      context: drought
      target: toolbox
    container_name: drought
    restart: always
    command: "/drought/run_viirs_product.sh"
    networks:
      - new_mexico_water
    volumes:
      - /new_mexico_VIIRS:/new_mexico_VIIRS
      - /static:/static
      - /GEOS5FP:/GEOS5FP
      - /LANCE:/LANCE
      - /SRTM:/SRTM
      - /VIIRS_output:/VIIRS_output

networks:
  new_mexico_water:
    driver: bridge
