version: "3.7"

services:
  app:
    build: app
    container_name: django-gunicorn
    restart: always
    env_file:
      - django.env
    ports:
      - "8000:8000"
    command: "gunicorn --workers=2 --bind=0.0.0.0:8000 mysite.wsgi:application"
    networks:
      - new_mexico_water
    volumes:
      - /water_rights_output:/water_rights_output

  drought:
    build:
      context: drought
      target: toolbox
    container_name: drought
    restart: always
    command: "/drought/run_viirs_product.sh"
    networks:
      - new_mexico_water
    volumes:
      - /new_mexico_VIIRS:/new_mexico_VIIRS
      - /static:/static
      - /GEOS5FP:/GEOS5FP
      - /LANCE:/LANCE
      - /SRTM:/SRTM
      - /VIIRS_output:/VIIRS_output

  cache:
    image: memcached
    ports:
      - "11211:11211"
    entrypoint:
      - memcached
      - -m 64
    networks:
      - new_mexico_water

  nginx:
    image: nginx:1.17
    container_name: ngx
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - app
    networks:
      - new_mexico_water

networks:
  new_mexico_water:
    driver: bridge
